<a href="https://colab.research.google.com/github/ZS4MLDL/learn_pytorch/blob/main/01_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
scalar = torch.tensor(1)
print(scalar)
print(scalar.item())
print(scalar.ndim)

tensor(1)
1
0


In [ ]:
vector = torch.tensor([1, 2])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 2])
1
torch.Size([2])


In [ ]:
vector = torch.tensor([[1,1]])
print(vector)
print(vector.ndim)

tensor([[1, 1]])
2


In [ ]:
vector = torch.tensor([[[1,3,2],[1,4,5]]])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([[[1, 3, 2],
         [1, 4, 5]]])
3
torch.Size([1, 2, 3])


In [ ]:
vector = torch.tensor([[[[1,3,2],[1,4,5]]]])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([[[[1, 3, 2],
          [1, 4, 5]]]])
4
torch.Size([1, 1, 2, 3])


In [ ]:
vector = torch.tensor([[[[[1,3,2],[1,4,5]]]]])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([[[[[1, 3, 2],
           [1, 4, 5]]]]])
5
torch.Size([1, 1, 1, 2, 3])


In [ ]:
random = torch.rand(size=(2, 2, 2, 1))
print(random)
print(random.ndim)

tensor([[[[0.1303],
          [0.7591]],

         [[0.7390],
          [0.0276]]],


        [[[0.6570],
          [0.4019]],

         [[0.4195],
          [0.0127]]]])
4


In [ ]:
ones = torch.zeros(size=(2,2))
print(ones)

tensor([[0., 0.],
        [0., 0.]])


In [ ]:
zeros = torch.zeros(size=(1,2))
print(zeros)

tensor([[0., 0.]])


In [ ]:
x = torch.arange(start=1, end=10, step=2)
print(x)

tensor([1, 3, 5, 7, 9])


In [ ]:
zero_like = torch.zeros_like(x)
print(zero_like)

tensor([0, 0, 0, 0, 0])


In [ ]:
one_like = torch.ones_like(x)
print(one_like)

tensor([1, 1, 1, 1, 1])


In [ ]:
eye = torch.eye(5)
print(eye)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
full = torch.full((2, 2), 7)
print(full)

tensor([[7, 7],
        [7, 7]])


In [ ]:
linear_space = torch.linspace(1, 10, 100)
print(linear_space)

tensor([ 1.0000,  1.0909,  1.1818,  1.2727,  1.3636,  1.4545,  1.5455,  1.6364,
         1.7273,  1.8182,  1.9091,  2.0000,  2.0909,  2.1818,  2.2727,  2.3636,
         2.4545,  2.5455,  2.6364,  2.7273,  2.8182,  2.9091,  3.0000,  3.0909,
         3.1818,  3.2727,  3.3636,  3.4545,  3.5455,  3.6364,  3.7273,  3.8182,
         3.9091,  4.0000,  4.0909,  4.1818,  4.2727,  4.3636,  4.4545,  4.5455,
         4.6364,  4.7273,  4.8182,  4.9091,  5.0000,  5.0909,  5.1818,  5.2727,
         5.3636,  5.4545,  5.5455,  5.6364,  5.7273,  5.8182,  5.9091,  6.0000,
         6.0909,  6.1818,  6.2727,  6.3636,  6.4545,  6.5455,  6.6364,  6.7273,
         6.8182,  6.9091,  7.0000,  7.0909,  7.1818,  7.2727,  7.3636,  7.4545,
         7.5455,  7.6364,  7.7273,  7.8182,  7.9091,  8.0000,  8.0909,  8.1818,
         8.2727,  8.3636,  8.4545,  8.5455,  8.6364,  8.7273,  8.8182,  8.9091,
         9.0000,  9.0909,  9.1818,  9.2727,  9.3636,  9.4545,  9.5455,  9.6364,
         9.7273,  9.8182,  9.9091, 10.00

In [ ]:
int_ = torch.arange(1,10, dtype=int)
print(int_)
float_ = torch.arange(1,10)
print(float_)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
float_= float_.type(torch.float16)
print(float_)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)


In [ ]:
tensor1 = torch.tensor([2, 3, 1])
tensor1 + 2

tensor([4, 5, 3])

In [ ]:
tensor2 = torch.tensor([1,2,3])
tensor2 - 10

tensor([-9, -8, -7])

In [ ]:
add = torch.add(tensor1, tensor2)
print(add)

tensor([3, 5, 4])


In [ ]:
add * 10

tensor([30, 50, 40])

In [ ]:
torch.mul(tensor2, add)

tensor([ 3, 10, 12])

In [ ]:
add / 10

tensor([0.3000, 0.5000, 0.4000])

In [ ]:
tensor1 @ tensor2

tensor(11)

In [ ]:
torch.matmul(tensor1, tensor2)

tensor(11)

In [ ]:
tensor1.shape

torch.Size([3])

In [ ]:
tensor2, tensor2.shape

(tensor([1, 2, 3]), torch.Size([3]))

In [ ]:
torch.min(tensor1)

tensor(1)

In [ ]:
torch.max(tensor2)

tensor(3)

In [ ]:
torch.mean(tensor2.type(torch.float16))

tensor(2., dtype=torch.float16)

In [ ]:
tensor2.argmin()

tensor(0)

In [ ]:
tensor2.argmax()

tensor(2)

In [ ]:
tensor3 = torch.arange(1, 10, 0.5)
tensor3

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
        5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

In [ ]:
tensor3.reshape(3, 6)

tensor([[1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000],
        [4.0000, 4.5000, 5.0000, 5.5000, 6.0000, 6.5000],
        [7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000]])

In [ ]:
tensor3.view((2, 9))

tensor([[1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000],
        [5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000]])

In [ ]:
tensor_stacked = torch.arange(10, 20,0.5)

In [ ]:
torch.stack([tensor_stacked,tensor_stacked,tensor_stacked], dim=1)

tensor([[10.0000, 10.0000, 10.0000],
        [10.5000, 10.5000, 10.5000],
        [11.0000, 11.0000, 11.0000],
        [11.5000, 11.5000, 11.5000],
        [12.0000, 12.0000, 12.0000],
        [12.5000, 12.5000, 12.5000],
        [13.0000, 13.0000, 13.0000],
        [13.5000, 13.5000, 13.5000],
        [14.0000, 14.0000, 14.0000],
        [14.5000, 14.5000, 14.5000],
        [15.0000, 15.0000, 15.0000],
        [15.5000, 15.5000, 15.5000],
        [16.0000, 16.0000, 16.0000],
        [16.5000, 16.5000, 16.5000],
        [17.0000, 17.0000, 17.0000],
        [17.5000, 17.5000, 17.5000],
        [18.0000, 18.0000, 18.0000],
        [18.5000, 18.5000, 18.5000],
        [19.0000, 19.0000, 19.0000],
        [19.5000, 19.5000, 19.5000]])

In [ ]:
import torch

In [ ]:
x = torch.tensor([[1,2,3], [2,3,4]])
x.shape

torch.Size([2, 3])

In [ ]:
x = x.unsqueeze(dim=0)
x.shape, x

(torch.Size([1, 2, 3]),
 tensor([[[1, 2, 3],
          [2, 3, 4]]]))

In [ ]:
x = x.unsqueeze(dim=1)
x, x.shape

(tensor([[[[1, 2, 3],
           [2, 3, 4]]]]),
 torch.Size([1, 1, 2, 3]))

In [ ]:
x = x.squeeze(dim=0)
x.shape

torch.Size([2, 3])

In [2]:
#permute