<a href="https://colab.research.google.com/github/ZS4MLDL/learn_pytorch/blob/main/03_SentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 25.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 14.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 9.7 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


In [3]:
!pip3 install torchtext==0.14.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 76.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 890.1/890.1 MB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 54.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 37.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 2.4 MB/s eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 2.5.1+cu121
    Uninstalling torch-2.5.1+cu121:
      Successfully uninstalled torch-2.5.1+cu121
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.5.1+cu121 requires torch==2.5.1, but you have torch 1.13.0 which is incompatible.
torchvision 0.20.1+cu121 requires torch==2.5.1, but you have torch 1.13.0 which is inco

In [4]:
import collections
import datasets
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
import torchtext
import tqdm

In [5]:
#Load datasets
#tokenize data
#split the data
#creating vocab
#numerical data
#convert to tensors
#create dataloaders

In [6]:
train_data, test_data = datasets.load_dataset("imdb", split=["train", "test"])

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

unsupervised-00000-of-00001.parquet:   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [7]:
train_data

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [8]:
test_data

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [9]:
train_data.features

{'text': Value(dtype='string', id=None),
 'label': ClassLabel(names=['neg', 'pos'], id=None)}

In [10]:
train_data[0]

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far be

In [11]:
tokenizer = torchtext.data.utils.get_tokenizer("basic_english")

In [12]:
tokenizer("hello world")

['hello', 'world']

In [13]:
  def tokenize_example(example, tokenizer, max_length):
    tokens = tokenizer(example["text"])[:max_length]
    return {"tokens": tokens}

In [14]:
max_length = 256

train_data = train_data.map(tokenize_example, fn_kwargs={"tokenizer": tokenizer, "max_length": max_length})
test_data = test_data.map(tokenize_example, fn_kwargs={"tokenizer":tokenizer, "max_length": max_length})

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

In [15]:
train_data, train_data[0] #tokens added to train data

(Dataset({
     features: ['text', 'label', 'tokens'],
     num_rows: 25000
 }),
 {'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this

In [16]:
train_data.features

{'text': Value(dtype='string', id=None),
 'label': ClassLabel(names=['neg', 'pos'], id=None),
 'tokens': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None)}

In [17]:
test_size = 0.25
train_valid_data = train_data.train_test_split(test_size=test_size)
train_data = train_valid_data['train']
valid_data = train_valid_data["test"]

len(train_data), len(test_data), len(valid_data)

(18750, 25000, 6250)

In [18]:
min_freq = 5
special_tokens = ["<unk>","<pad>"]

vocab = torchtext.vocab.build_vocab_from_iterator(
    train_data["tokens"],
    min_freq = min_freq,
    specials = special_tokens,
)

In [19]:
len(vocab), vocab.get_itos()[:10], vocab["and"]

(21651, ['<unk>', '<pad>', 'the', '.', ',', 'a', 'and', 'of', 'to', "'"], 6)

In [20]:
unk_index = vocab["<unk>"]
pad_index = vocab["<pad>"]

unk_index, pad_index

(0, 1)

In [21]:
vocab.set_default_index(unk_index)

In [22]:
vocab.lookup_indices(["hello", "world"])

[4855, 188]

In [23]:
def numericalize_example(example, vocab):
  ids = vocab.lookup_indices(example["tokens"])
  return {"ids": ids}


In [24]:
train_data = train_data.map(numericalize_example, fn_kwargs={"vocab":vocab})
test_data = test_data.map(numericalize_example, fn_kwargs={"vocab":vocab})
valid_data = valid_data.map(numericalize_example, fn_kwargs={"vocab":vocab})

Map:   0%|          | 0/18750 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/6250 [00:00<?, ? examples/s]

In [25]:
train_data

Dataset({
    features: ['text', 'label', 'tokens', 'ids'],
    num_rows: 18750
})

In [26]:
#converting to tensor [ids , labels]
train_data = train_data.with_format(type="torch", columns=["ids", "label"])
test_data = test_data.with_format(type="torch", columns=["ids", "label"])
valid_data = valid_data.with_format(type="torch", columns=["ids", "label"])

In [27]:
train_data[0]["label"], train_data[0]["ids"]

(tensor(1),
 tensor([   14,    18,   389,  3523,  4658,     4,     7,  2727,     2,  4998,
          2180,     3,    14,    18,    47,    34,   132,     9,    16,  3025,
           310,   293,    37,     5,  4727,   130,     5,  3516,  9813,    10,
           122,  1642,     3,     5,  3516,  1239,  2773,     6,  3688,   105,
           682,  9691,    13,   120,    25,    37,    80,  1877,    24,    20,
             5,   249,     4,   264,    40,  3523,  4658,     3,    63,   682,
            21,    14,  8672,     7,     5,   132,     4,    42,    10,  2259,
            20,  3516,     3,    14,    10,    38,    37,     2, 11948,     7,
            49,   450,     4,    42,    10,   243,    62,   920,    13,   289,
            49,    20,   173,   181,  4772,     5,  2150,  4772,     3,    49,
           450,   853,    15,    14,    10,    48,     5,  2962,  4183,    21,
             2,   181,   249,     4,    19,    63,    51,     5,  7944,     8,
           203,    13,  1070,  1291,    

In [28]:
def get_collate_fn(pad_index):
  def collate_fn(batch):
    batch_ids = [i["ids"] for i in batch]
    batch_ids = nn.utils.rnn.pad_sequence(batch_ids, padding_value=pad_index, batch_first=True)

    batch_label = [i["label"] for i in batch]
    batch_label = torch.stack(batch_label)
    batch = {"ids": batch_ids, "label":batch_label}
    return batch

  return collate_fn

In [29]:
def get_data_loader(dataset, batch_size, pad_index, shuffle=False):
  collate_fn = get_collate_fn(pad_index)
  data_loader = torch.utils.data.DataLoader(
      dataset = dataset,
      batch_size = batch_size,
      collate_fn = collate_fn,
      shuffle = shuffle
  )
  return data_loader

In [30]:
batch_size = 512
train_data_loader = get_data_loader(train_data, batch_size, pad_index, shuffle=True)
valid_data_loader = get_data_loader(valid_data, batch_size, pad_index)
test_data_loader = get_data_loader(test_data, batch_size, pad_index)

In [31]:
len(train_data_loader), len(valid_data_loader), len(test_data_loader)

(37, 13, 49)

In [54]:
#Build Model
class NBow(nn.Module):
  def __init__(self, vocab_size, embedding_dim, output_dim, pad_index):
    super().__init__()
    self.embedding  = nn.Embedding(vocab_size, embedding_dim, padding_idx=pad_index)
    self.fc = nn.Linear(embedding_dim, output_dim)

  def forward(self, ids):
    #ids = [batch size, seq len]
    embedded = self.embedding(ids)
    #embedded = [batch size, seq len, embedding dim]
    pooled = embedded.mean(dim=1)
    #embedded = [batch size, embedding dim]
    prediction = self.fc(pooled)
    #prediction = [batch size, output dim]
    return prediction

In [55]:
vocab_size = len(vocab)
embedding_dim = 300
output_dim = len(train_data.unique("label"))
model = NBow(vocab_size, embedding_dim, output_dim, pad_index)

In [56]:
model

NBow(
  (embedding): Embedding(21651, 300, padding_idx=1)
  (fc): Linear(in_features=300, out_features=2, bias=True)
)

In [57]:
def count_parameters(model):
  return sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Model has { count_parameters(model):,} trainable parameters")

Model has 6,495,902 trainable parameters


In [58]:
vectors = torchtext.vocab.GloVe()

In [59]:
vectors.get_vecs_by_tokens("hello"), vectors.get_vecs_by_tokens("hello").shape

(tensor([ 0.2523,  0.1018, -0.6748,  0.2112,  0.4349,  0.1654,  0.4826, -0.8122,
          0.0413,  0.7850, -0.0779, -0.6632,  0.1464, -0.2929, -0.2549,  0.0193,
         -0.2026,  0.9823,  0.0283, -0.0813, -0.1214,  0.1313, -0.1765,  0.1356,
         -0.1636, -0.2257,  0.0550, -0.2031,  0.2072,  0.0958,  0.2248,  0.2154,
         -0.3298, -0.1224, -0.4003, -0.0794, -0.1996, -0.0151, -0.0791, -0.1813,
          0.2068, -0.3620, -0.3074, -0.2442, -0.2311,  0.0980,  0.1463, -0.0627,
          0.4293, -0.0780, -0.1963,  0.6509, -0.2281, -0.3031, -0.1248, -0.1757,
         -0.1465,  0.1536, -0.2952,  0.1510, -0.5173, -0.0336, -0.2311, -0.7833,
          0.0180, -0.1572,  0.0229,  0.4964,  0.0292,  0.0567,  0.1462, -0.1919,
          0.1624,  0.2390,  0.3643,  0.4526,  0.2456,  0.2380,  0.3140,  0.3487,
         -0.0358,  0.5611, -0.2535,  0.0520, -0.1062, -0.3096,  1.0585, -0.4202,
          0.1822, -0.1126,  0.4058,  0.1178, -0.1971, -0.0753,  0.0807, -0.0278,
         -0.1562, -0.4468, -

In [60]:
pretrained_embeddings = vectors.get_vecs_by_tokens(vocab.get_itos())
pretrained_embeddings.shape

torch.Size([21651, 300])

In [61]:
model.embedding.weight

Parameter containing:
tensor([[ 1.3163e-01, -1.0839e-03, -1.0406e+00,  ..., -3.8876e-01,
         -1.0414e+00,  8.1824e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 1.3528e+00,  1.1844e+00,  5.1162e-01,  ..., -6.4134e-01,
         -3.3997e-01, -5.4516e-02],
        ...,
        [ 1.2597e+00, -3.5909e-01, -2.3277e-01,  ..., -1.5119e-01,
          2.0006e+00, -1.4032e+00],
        [-9.0891e-01, -1.2949e+00,  3.9246e-02,  ..., -1.1785e-01,
         -2.7016e-01, -8.5232e-01],
        [-5.2091e-01,  3.3619e-01,  2.8035e-01,  ...,  1.7617e+00,
         -5.9456e-01,  1.1843e+00]], requires_grad=True)

In [62]:
pretrained_embeddings

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.2720, -0.0620, -0.1884,  ...,  0.1302, -0.1832,  0.1323],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.1349,  0.1143,  0.2112,  ...,  0.3040, -0.6853,  0.2070],
        [-0.1503,  0.5624, -0.5622,  ..., -0.4224, -0.6836,  0.0726]])

In [63]:
model.embedding.weight.data = pretrained_embeddings


In [64]:
optimizer =optim.Adam(model.parameters())
criterion = nn.CrossEntropyLoss()
device  = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)
criterion = criterion.to(device)

In [77]:
def train(data_loader,model,criterion, optimizer, device):
  model.train()
  epoch_losses = []
  epoch_accs = []

  for batch in tqdm.tqdm(data_loader, desc="training.."):
    ids = batch["ids"].to(device)
    label = batch["label"].to(device)
    prediction = model(ids)
    loss = criterion(prediction, label)

    accuracy = get_accuracy(prediction, label)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    epoch_losses.append(loss.item())
    epoch_accs.append(accuracy.item())

  return np.mean(epoch_losses), np.mean(epoch_accs)


In [76]:
def evaluate(data_loader, model, criterion, device):
  model.eval()
  epoch_losses=[]
  epoch_accs=[]

  with torch.no_grad():
    for batch in tqdm.tqdm(data_loader, desc="evaluating.."):
      ids = batch["ids"].to(device)
      label = batch["label"].to(device)
      prediction = model(ids)
      loss=criterion(prediction, label)
      accuracy = get_accuracy(prediction, label)
      epoch_losses.append(loss.item())
      epoch_accs.append(accuracy.item())
  return np.mean(epoch_losses), np.mean(epoch_accs)

In [79]:
def get_accuracy(prediction, label):

  batch_size,_ = prediction.shape

  predicted_classes = prediction.argmax(dim=-1)
  correct_prediction = predicted_classes.eq(label).sum()
  accuracy = correct_prediction / batch_size

  return accuracy


In [82]:
n_epochs = 10
best_valid_loss=float("inf")
metrics = collections.defaultdict(list)

for epoch in range(n_epochs):
  train_loss, train_accs = train(
                                train_data_loader,
                                model,
                                criterion,
                                optimizer,
                                device
                                )
  valid_loss, valid_accs = evaluate(
                                valid_data_loader,
                                model,
                                criterion,
                                device
                                )
  metrics["train_losses"].append(train_loss)
  metrics["train_accs"].append(train_acc)
  metrics["valid_losses"].append(valid_loss)
  metrics["valid_accs"].append(valid_acc)

  if valid_loss < best_valid_loss:
    best_valid_loss = valid_loss
    torch.save(model.state_dict(), "nbow.pt")

  print(f"epochs: {epoch}")
  print(f"train loss: {train_loss:.3f}, train accuracy :{train_accs:.3f}")
  print(f"valid loss: {valid_loss:.3f}, valid accuracy :{valid_accs:.3f}")

evaluating..: 100%|██████████| 13/13 [00:02<00:00,  5.51it/s]


epochs: 0
train loss: 0.579, train accuracy :0.774
valid loss: 0.552, valid accuracy :0.781


evaluating..: 100%|██████████| 13/13 [00:01<00:00,  6.63it/s]


epochs: 1
train loss: 0.507, train accuracy :0.813
valid loss: 0.487, valid accuracy :0.821


evaluating..: 100%|██████████| 13/13 [00:01<00:00,  6.65it/s]


epochs: 2
train loss: 0.439, train accuracy :0.848
valid loss: 0.433, valid accuracy :0.845


evaluating..: 100%|██████████| 13/13 [00:02<00:00,  4.81it/s]


epochs: 3
train loss: 0.384, train accuracy :0.870
valid loss: 0.394, valid accuracy :0.854


evaluating..: 100%|██████████| 13/13 [00:01<00:00,  6.61it/s]


epochs: 4
train loss: 0.342, train accuracy :0.885
valid loss: 0.365, valid accuracy :0.862


evaluating..: 100%|██████████| 13/13 [00:01<00:00,  6.68it/s]


epochs: 5
train loss: 0.310, train accuracy :0.897
valid loss: 0.344, valid accuracy :0.869


evaluating..: 100%|██████████| 13/13 [00:02<00:00,  6.16it/s]


epochs: 6
train loss: 0.283, train accuracy :0.905
valid loss: 0.328, valid accuracy :0.874


evaluating..: 100%|██████████| 13/13 [00:02<00:00,  6.41it/s]


epochs: 7
train loss: 0.260, train accuracy :0.915
valid loss: 0.316, valid accuracy :0.879


evaluating..: 100%|██████████| 13/13 [00:01<00:00,  6.59it/s]


epochs: 8
train loss: 0.240, train accuracy :0.922
valid loss: 0.306, valid accuracy :0.885


evaluating..: 100%|██████████| 13/13 [00:02<00:00,  6.44it/s]

epochs: 9
train loss: 0.223, train accuracy :0.930
valid loss: 0.299, valid accuracy :0.886


In [83]:
 model.load_state_dict(torch.load("nbow.pt"))
 test_loss, test_acc = evaluate(test_data_loader, model, criterion, device)

evaluating..: 100%|██████████| 49/49 [00:09<00:00,  5.36it/s]


In [86]:
print(f"test_loss { test_loss:.3f}")
print(f"test_acc { test_acc:.3f}")

test_loss 0.336
test_acc 0.863


In [89]:
def predict_sentiment(text, model, tokenizer, vocab, device):
    tokens=tokenizer(text)
    ids=vocab.lookup_indices(tokens)
    tensor=torch.LongTensor(ids).unsqueeze(dim=0).to(device)
    prediction=model(tensor).squeeze(dim=0)
    probability=torch.softmax(prediction,dim=-1)
    predicted_class=prediction.argmax(dim=-1).item()
    predicted_probability=probability[predicted_class].item()
    return predicted_class,predicted_probability



In [90]:

text="this film is terrible"
predict_sentiment(text,model,tokenizer,vocab,device)


(0, 1.0)